/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "student.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <rpc/rpc.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
add_student_1(student *argp, CLIENT *clnt)
{
    static int clnt_res;

    memset((char *)&clnt_res, 0, sizeof(clnt_res));
    if (clnt_call (clnt, ADD_STUDENT,
        (xdrproc_t) xdr_student, (caddr_t) argp,
        (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
        TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

int main (int argc, char **argv) {
    CLIENT *cl;
    char *server;
    char *student_details;
    int *result;

    // Check command-line arguments
    if (argc != 2) {
        printf("Usage: %s <server IP address>\n", argv[0]);
        exit(1);
    }

    // Create client handle
    server = argv[1];
    cl = clnt_create(server, STUDENT_PROG, STUDENT_VERS, "tcp");
    if (cl == NULL) {
        clnt_pcreateerror(server);
        exit(1);
    }

    // Get the student's details from the user
    struct Student student;
    printf("Enter the student's details:\n");
    printf("Serial Number: ");
    scanf("%d", &student.serialNumber);
    printf("Registration Number: ");
    scanf("%s", student.regNumber);
    printf("First Name: ");
    scanf("%s", student.firstName);
    printf("Last Name: ");
    scanf("%s", student.lastName);

    // Send the student's details to the server
    student_details = malloc(strlen(student.regNumber) + strlen(student.firstName) + strlen(student.lastName) + 50);
    sprintf(student_details, "%d %s %s %s", student.serialNumber, student.regNumber, student.firstName, student.lastName);
    result = add_student_1(&student_details, cl);
    if (result == NULL) {
        clnt_perror(cl, server);
        exit(1);
    }
    printf("Student data sent successfully.\n");

    // Clean up
    free(student_details);
    clnt_destroy(cl);
    return 0;
}
