/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "student.h"

bool_t
xdr_Student (XDR *xdrs, Student *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->serialNumber))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->regNumber, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->firstName, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->lastName, 50))
		 return FALSE;
	return TRUE;
}
