/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <unistd.h>
#include "student.h"
#define MAX_NAME_LENGTH 50
#define FILENAME "student.txt"

int checkIfSerialNumberExists(int serialNumber) {
    FILE *file;
    char file_data[MAX_NAME_LENGTH * 2 * sizeof(int) * 2];
    file = fopen(FILENAME, "r");
    while (fgets(file_data, sizeof(file_data), file) != NULL) {
        struct Student temp_student;
        sscanf(file_data, "%d\t\t\t\t\t\t %s\t\t\t\t\t\t %s %s\n", &temp_student.serialNumber, temp_student.regNumber, temp_student.firstName, temp_student.lastName);
        if (temp_student.serialNumber == serialNumber) {
            fclose(file);
            return 1;
        }
    }
    fclose(file);
    return 0;
}

int checkIfRegNumberExists(char* regNumber) {
    FILE *file;
    char file_data[MAX_NAME_LENGTH * 2 * sizeof(int) * 2];
    file = fopen(FILENAME, "r");
    while (fgets(file_data, sizeof(file_data), file) != NULL) {
        struct Student temp_student;
        sscanf(file_data, "%d\t\t\t\t\t\t %s\t\t\t\t\t\t %s %s\n", &temp_student.serialNumber, temp_student.regNumber, temp_student.firstName, temp_student.lastName);
        if (strcmp(temp_student.regNumber, regNumber) == 0) {
            fclose(file);
            return 1;
        }
    }
    fclose(file);
    return 0;
}

int *add_student_1_svc(Student *student, struct svc_req *rqstp) {
    static int result = 0;
    if (checkIfSerialNumberExists(student->serialNumber)) {
        result = -1;
    } else if (checkIfRegNumberExists(student->regNumber)) {
        result = -2;
    } else {
        FILE *file;
        file = fopen(FILENAME, "a");
        if (file == NULL) {
            perror("Error opening file");
        } else {
            // Write Column Headers
            if (ftell(file) == 0) {
                fprintf(file, "Serial Number\t\t\t Registration Number\t\t\t\t\t Name\n");
            }
            fprintf(file, "%d\t\t\t\t\t\t %s\t\t\t\t\t\t %s %s\n", student->serialNumber, student->regNumber, student->firstName, student->lastName);
            fclose(file);
            result = 0; // success
        }
    }
    return &result;
}