/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "student.h"
#define MAX_NAME_LENGTH 50

void
studentprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	Student add_student_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, STUDENTPROG, STUDENTVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int serialNumber;
    char regNumber[MAX_NAME_LENGTH];
    char firstName[MAX_NAME_LENGTH];
    char lastName[MAX_NAME_LENGTH];

	// Get the student's details from the user
    printf("Enter the student's details:\n");
    printf("Serial Number: ");
    scanf("%d", &serialNumber);
    printf("Registration Number: ");
    scanf("%s", regNumber);
    printf("First Name: ");
    scanf("%s", firstName);
    printf("Last Name: ");
    scanf("%s", lastName);

	struct Student student = {
        .serialNumber = serialNumber,
        .regNumber = regNumber,
        .firstName = firstName,
        .lastName = lastName
    };

	result_1 = add_student_1(&student, clnt);
	if (result_1 == (int *) NULL) 
	{
		clnt_perror(clnt, "call failed");
	}

	switch (*result_1) {
        case 0:
            printf("Student added successfully\n");
            break;
        case -1:
            printf("Error: Student with serial number %d already exists\n", serialNumber);
            break;
        case -2:
            printf("Error: Student with registration number %s already exists\n", regNumber);
            break;
        default:
            printf("Error: Unknown error occurred\n");
            break;
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("Usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	studentprog_1 (host);
exit (0);
}
