/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STUDENT_H_RPCGEN
#define _STUDENT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Student {
	int serialNumber;
	char *regNumber;
	char *firstName;
	char *lastName;
};
typedef struct Student Student;

#define STUDENTPROG 0x20000001
#define STUDENTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add_student 1
extern  int * add_student_1(Student *, CLIENT *);
extern  int * add_student_1_svc(Student *, struct svc_req *);
extern int studentprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add_student 1
extern  int * add_student_1();
extern  int * add_student_1_svc();
extern int studentprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Student (XDR *, Student*);

#else /* K&R C */
extern bool_t xdr_Student ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STUDENT_H_RPCGEN */
