/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
calculate_1_svc(calculator_input *argp, struct svc_req *rqstp)
{
    static int result;
    printf("Calculate Procedure Called\n");
    printf("Received operator: %c\n", *argp->op);
    switch (*argp->op) {
        case '+':
            result = argp->num1 + argp->num2;
            break;
        case '-':
            result = argp->num1 - argp->num2;
            break;
        case '*':
            result = argp->num1 * argp->num2;
            break;
        case '/':
            if (argp->num2 == 0) {
                printf("Division by zero\n");
                exit(1);
            }
            result = argp->num1 / argp->num2;
            break;
        default:
            printf("Invalid operator\n");
            exit(1);
            break;
    }

    static int count = 0;
    if (++count == 1) {
        svc_exit();
    }

    // send the result back to the client
    return (&result);
}
